const featuredProducts = [
  {
    name: "Organic Beetroot Powder",
    category: "Vegetable Powders",
    desc: "Pure organic beetroot powder, rich in antioxidants and nitrates",
    price: 24.99,
    oldPrice: 32.99,
    rating: 4,
    reviews: 324,
    image: "/images/beetroot.jpg",
    offer: "24% OFF",
  },
  {
    name: "Kale & Spinach Chips",
    category: "Vegetable Snacks",
    desc: "Crispy baked kale and spinach chips with sea salt",
    price: 12.99,
    oldPrice: 16.99,
    rating: 5,
    reviews: 567,
    image: "/images/kale-chips.jpg",
    offer: "24% OFF",
  },
  {
    name: "Mixed Berry Powder Blend",
    category: "Fruit Powders",
    desc: "Blend of organic strawberry, blueberry, and raspberry powder",
    price: 28.99,
    oldPrice: 36.99,
    rating: 4,
    reviews: 892,
    image: "/images/berry-powder.jpg",
    offer: "22% OFF",
  },
  {
    name: "Dried Mango Slices",
    category: "Fruit Snacks",
    desc: "Sweet and chewy organic dried mango slices, no added sugar",
    price: 15.99,
    oldPrice: null,
    rating: 4,
    reviews: 445,
    image: "/images/mango.jpg",
    offer: null,
  },
  {
    name: "Dried Mango Slices",
    category: "Fruit Snacks",
    desc: "Sweet and chewy organic dried mango slices, no added sugar",
    price: 15.99,
    oldPrice: null,
    rating: 4,
    reviews: 445,
    image: "/images/mango.jpg",
    offer: null,
  },
];

export default featuredProducts;
